baseURL = "https://geekkery.4everland.app/"
languageCode = "zh-cn"
title = "GeekKery"
theme = "hugo-theme-cactus"
copyright = "GeekKery" # cactus will use title if copyright is not set
# googleAnalytics = "UA-1234-5"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2
[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 4
[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 4

[params]
colortheme = "classic" # dark, light, white, or classic
rss = true # generate rss feed. default value is false
#googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
showAllPostsArchive = true # default
# Home page settings
description = "GeekKery | Jayden 的个人博客 | web 前端技术文章"
typedContent = "于是妖童媛女，荡舟心许，鹢首徐回，兼传羽杯。棹将移而藻挂，船欲动而萍开。^1000\n尔其纤腰束素，迁延顾步。夏始春余，叶嫩花初。恐沾裳而浅笑，畏倾船而敛裾。"
mainSection = "posts" # your main section
mainSectionTitle = "Writings"
showAllPostsOnHomePage = true # default
postsOnHomePage = 7 # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = false # show tags overview by default.
showProjectsList = false # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/geekkery" # title link for projects list
# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default
# Post page settings
show_updated = true # default
showReadTime = true # default
#serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
#serverName = "" # Defaults to cactus.chat

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
name = "github"
link = "https://github.com/geekkery"
[[params.social]]
name = "linkedin"
link = "https://www.linkedin.cn/injobs/in/jayden-deng-3654b1176"
[[params.social]]
name = "email"
link = "dqy676081195@gmail.com"  # no need for "mailto:" in the head
