######################## default configuration ####################
baseURL = "https://www.soupcraft.icu/"
title = "GeeKery | 高手分割线"
theme = "bookworm"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
# disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.80.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
# [[params.plugins.js]]
# link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Noto Sans SC"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#363636"
light = "#FAFAFA"
color_primary = "#01AD9F"

[markup]
defaultMarkdownHandler = "blackfriday"

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "native"
tabWidth = 4

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"
favicon = "images/favicon.ico"
# Meta data
description = "GeeKery 高手分割线"
author = "GeeKery"
# contact form action
# contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Copyright © 2021 GeeKery"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = "bookworm"
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
weight = 1
url = "/"
name = "Home"

[[menu.main]]
weight = 2
url = "categories"
name = "Categories"

[[menu.main]]
weight = 3
url = "tags"
name = "Tags"

[[menu.main]]
weight = 4
url = "about"
name = "About"

############################# Footer Menu ########################
[[menu.footer]]
weight = 1
url = "https://beian.miit.gov.cn/"
name = "蜀ICP备20010312号-1"

[[params.social]]
url = "https://www.linkedin.com/in/jayden-deng-3654b1176"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome

[[params.social]]
url = "mailto:mailto:dqy676081195@gmail.com"
icon = "las la-envelope-open-text" # https://icons8.com/line-awesome

[[params.social]]
url = "https://github.com/GeekKery"
icon = "lab la-github" # https://icons8.com/line-awesome
